create table if not exists jobs (
  id bigint generated by default as identity primary key,
  company text not null,
  title text not null,
  location text,
  url text,
  source text,
  published_at date,
  description text,
  seniority text,
  status text default 'À analyser',
  score integer,
  note text,
  created_at timestamptz default now()
);

create index if not exists jobs_status_idx on jobs(status);
create index if not exists jobs_published_idx on jobs(published_at desc);
